### ISSUE TITLE
Implement backtracking procedure

### ISSUE THREAD

**Issue by Hargre** [SMA-FGA/dcop-adopt#8]
- [x] Minimize local cost for upper bound

- [x] Minimize local cost for lower bound

- [x] Send value message to lower neighbours (currently only sends to children)

- [x] Call mantain allocation invariant

- [ ] Add termination logic

- [x] Send cost message to parent

**Comment by Jefersonalves** [comment]
An initial termination logic was created but didn't work because the agent died before sending the termination message. This problem is now addressed in question #22.
